-- =========================================================
-- Auto-generated: Full schema + seed data for IMDb Top 20 movies
-- Notes:
-- - release_date is set to YYYY-01-01 (placeholder) because only year was available.
-- - duration_minutes / age_rating left NULL (you can update later).
-- =========================================================

-- Clean start (optional)
DROP TABLE IF EXISTS favorites CASCADE;
DROP TABLE IF EXISTS movie_cast CASCADE;
DROP TABLE IF EXISTS movie_genres CASCADE;
DROP TABLE IF EXISTS persons CASCADE;
DROP TABLE IF EXISTS genres CASCADE;
DROP TABLE IF EXISTS movies CASCADE;
DROP TABLE IF EXISTS users CASCADE;

DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_type WHERE typname = 'user_role') THEN
    DROP TYPE user_role;
  END IF;
EXCEPTION WHEN others THEN
  -- ignore
END $$;

CREATE TYPE user_role AS ENUM ('user','admin');

CREATE TABLE users (
  user_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username VARCHAR(50) UNIQUE NOT NULL,
  email VARCHAR(100) UNIQUE NOT NULL,
  password_hash VARCHAR(255) NOT NULL,
  full_name VARCHAR(100),
  role user_role DEFAULT 'user',
  created_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE movies (
  movie_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title VARCHAR(255) UNIQUE NOT NULL,
  release_date DATE,
  duration_minutes INT,
  age_rating VARCHAR(10),
  imdb_rank INT
);

CREATE TABLE genres (
  genre_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(50) UNIQUE NOT NULL
);

CREATE TABLE persons (
  person_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(255) UNIQUE NOT NULL
);

CREATE TABLE movie_genres (
  movie_id INT NOT NULL REFERENCES movies(movie_id) ON DELETE CASCADE,
  genre_id INT NOT NULL REFERENCES genres(genre_id) ON DELETE RESTRICT,
  PRIMARY KEY (movie_id, genre_id)
);

CREATE TABLE movie_cast (
  cast_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  movie_id INT NOT NULL REFERENCES movies(movie_id) ON DELETE CASCADE,
  person_id INT NOT NULL REFERENCES persons(person_id) ON DELETE CASCADE,
  job VARCHAR(30) NOT NULL,
  character_name VARCHAR(255),
  billing_order INT
);

CREATE TABLE favorites (
  user_id INT NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
  movie_id INT NOT NULL REFERENCES movies(movie_id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ DEFAULT now(),
  PRIMARY KEY (user_id, movie_id)
);

-- =========================
-- Seed: movies (IMDb Top 20)
-- =========================
INSERT INTO movies (title, release_date, duration_minutes, age_rating, imdb_rank)
VALUES
  ('The Shawshank Redemption', DATE '1994-01-01', NULL, NULL, 1),
  ('The Godfather', DATE '1972-01-01', NULL, NULL, 2),
  ('The Dark Knight', DATE '2008-01-01', NULL, NULL, 3),
  ('The Godfather Part II', DATE '1974-01-01', NULL, NULL, 4),
  ('12 Angry Men', DATE '1957-01-01', NULL, NULL, 5),
  ('The Lord of the Rings: The Return of the King', DATE '2003-01-01', NULL, NULL, 6),
  ('Schindler''s List', DATE '1993-01-01', NULL, NULL, 7),
  ('The Lord of the Rings: The Fellowship of the Ring', DATE '2001-01-01', NULL, NULL, 8),
  ('Pulp Fiction', DATE '1994-01-01', NULL, NULL, 9),
  ('The Good, the Bad and the Ugly', DATE '1966-01-01', NULL, NULL, 10),
  ('Forrest Gump', DATE '1994-01-01', NULL, NULL, 11),
  ('The Lord of the Rings: The Two Towers', DATE '2002-01-01', NULL, NULL, 12),
  ('Fight Club', DATE '1999-01-01', NULL, NULL, 13),
  ('Inception', DATE '2010-01-01', NULL, NULL, 14),
  ('Star Wars: Episode V - The Empire Strikes Back', DATE '1980-01-01', NULL, NULL, 15),
  ('The Matrix', DATE '1999-01-01', NULL, NULL, 16),
  ('Goodfellas', DATE '1990-01-01', NULL, NULL, 17),
  ('Interstellar', DATE '2014-01-01', NULL, NULL, 18),
  ('One Flew Over the Cuckoo''s Nest', DATE '1975-01-01', NULL, NULL, 19),
  ('Se7en', DATE '1995-01-01', NULL, NULL, 20);

-- =========
-- Seed: genres
-- =========
INSERT INTO genres (name) VALUES
  ('Action'),
  ('Adventure'),
  ('Biography'),
  ('Crime'),
  ('Drama'),
  ('Fantasy'),
  ('History'),
  ('Mystery'),
  ('Romance'),
  ('Sci-Fi'),
  ('Thriller'),
  ('War'),
  ('Western')
ON CONFLICT (name) DO NOTHING;

-- =========
-- Seed: persons (directors + top billed cast)
-- =========
INSERT INTO persons (name) VALUES
  ('Aaron Eckhart'),
  ('Al Pacino'),
  ('Anne Hathaway'),
  ('Ben Kingsley'),
  ('Bob Gunton'),
  ('Brad Pitt'),
  ('Carrie Fisher'),
  ('Carrie-Anne Moss'),
  ('Christian Bale'),
  ('Christopher Nolan'),
  ('Clint Eastwood'),
  ('David Fincher'),
  ('Diane Keaton'),
  ('Edward Norton'),
  ('Eli Wallach'),
  ('Elijah Wood'),
  ('Elliot Page'),
  ('Francis Ford Coppola'),
  ('Frank Darabont'),
  ('Gary Sinise'),
  ('Harrison Ford'),
  ('Heath Ledger'),
  ('Helena Bonham Carter'),
  ('Henry Fonda'),
  ('Ian McKellen'),
  ('Irvin Kershner'),
  ('Jack Nicholson'),
  ('James Caan'),
  ('Jessica Chastain'),
  ('Joe Pesci'),
  ('John Travolta'),
  ('Joseph Gordon-Levitt'),
  ('Keanu Reeves'),
  ('Kevin Spacey'),
  ('Lana Wachowski'),
  ('Laurence Fishburne'),
  ('Lee J. Cobb'),
  ('Lee Van Cleef'),
  ('Leonardo DiCaprio'),
  ('Liam Neeson'),
  ('Lilly Wachowski'),
  ('Louise Fletcher'),
  ('Mark Hamill'),
  ('Marlon Brando'),
  ('Martin Balsam'),
  ('Martin Scorsese'),
  ('Matthew McConaughey'),
  ('Miloš Forman'),
  ('Morgan Freeman'),
  ('Peter Jackson'),
  ('Quentin Tarantino'),
  ('Ralph Fiennes'),
  ('Ray Liotta'),
  ('Robert De Niro'),
  ('Robert Zemeckis'),
  ('Robin Wright'),
  ('Samuel L. Jackson'),
  ('Sean Astin'),
  ('Sergio Leone'),
  ('Sidney Lumet'),
  ('Steven Spielberg'),
  ('Tim Robbins'),
  ('Tom Hanks'),
  ('Uma Thurman'),
  ('Viggo Mortensen'),
  ('Will Sampson')
ON CONFLICT (name) DO NOTHING;

-- =================
-- Seed: movie_genres
-- =================
WITH v(title, genre) AS (
  VALUES
    ('The Shawshank Redemption','Drama'),
    ('The Godfather','Crime'),
    ('The Godfather','Drama'),
    ('The Dark Knight','Action'),
    ('The Dark Knight','Crime'),
    ('The Dark Knight','Drama'),
    ('The Dark Knight','Thriller'),
    ('The Godfather Part II','Crime'),
    ('The Godfather Part II','Drama'),
    ('12 Angry Men','Drama'),
    ('Schindler''s List','Biography'),
    ('Schindler''s List','Drama'),
    ('Schindler''s List','History'),
    ('Schindler''s List','War'),
    ('The Lord of the Rings: The Return of the King','Adventure'),
    ('The Lord of the Rings: The Return of the King','Fantasy'),
    ('The Lord of the Rings: The Return of the King','Action'),
    ('The Lord of the Rings: The Return of the King','Drama'),
    ('The Lord of the Rings: The Fellowship of the Ring','Adventure'),
    ('The Lord of the Rings: The Fellowship of the Ring','Fantasy'),
    ('The Lord of the Rings: The Fellowship of the Ring','Action'),
    ('Pulp Fiction','Crime'),
    ('Pulp Fiction','Drama'),
    ('The Good, the Bad and the Ugly','Western'),
    ('The Good, the Bad and the Ugly','Adventure'),
    ('Forrest Gump','Drama'),
    ('Forrest Gump','Romance'),
    ('The Lord of the Rings: The Two Towers','Adventure'),
    ('The Lord of the Rings: The Two Towers','Fantasy'),
    ('The Lord of the Rings: The Two Towers','Action'),
    ('Fight Club','Drama'),
    ('Fight Club','Thriller'),
    ('Inception','Action'),
    ('Inception','Sci-Fi'),
    ('Inception','Thriller'),
    ('Star Wars: Episode V - The Empire Strikes Back','Action'),
    ('Star Wars: Episode V - The Empire Strikes Back','Adventure'),
    ('Star Wars: Episode V - The Empire Strikes Back','Sci-Fi'),
    ('The Matrix','Action'),
    ('The Matrix','Sci-Fi'),
    ('Goodfellas','Biography'),
    ('Goodfellas','Crime'),
    ('Goodfellas','Drama'),
    ('Interstellar','Adventure'),
    ('Interstellar','Drama'),
    ('Interstellar','Sci-Fi'),
    ('One Flew Over the Cuckoo''s Nest','Drama'),
    ('Se7en','Crime'),
    ('Se7en','Drama'),
    ('Se7en','Mystery'),
    ('Se7en','Thriller')
)
INSERT INTO movie_genres(movie_id, genre_id)
SELECT m.movie_id, g.genre_id
FROM v
JOIN movies m ON m.title = v.title
JOIN genres g ON g.name = v.genre
ON CONFLICT DO NOTHING;

-- ================
-- Seed: movie_cast
-- ================
WITH v(title, person, job, character_name, billing_order) AS (
  VALUES
    ('The Shawshank Redemption','Frank Darabont','director',NULL,NULL),
    ('The Godfather','Francis Ford Coppola','director',NULL,NULL),
    ('The Dark Knight','Christopher Nolan','director',NULL,NULL),
    ('The Godfather Part II','Francis Ford Coppola','director',NULL,NULL),
    ('12 Angry Men','Sidney Lumet','director',NULL,NULL),
    ('Schindler''s List','Steven Spielberg','director',NULL,NULL),
    ('The Lord of the Rings: The Return of the King','Peter Jackson','director',NULL,NULL),
    ('The Lord of the Rings: The Fellowship of the Ring','Peter Jackson','director',NULL,NULL),
    ('Pulp Fiction','Quentin Tarantino','director',NULL,NULL),
    ('The Good, the Bad and the Ugly','Sergio Leone','director',NULL,NULL),
    ('Forrest Gump','Robert Zemeckis','director',NULL,NULL),
    ('The Lord of the Rings: The Two Towers','Peter Jackson','director',NULL,NULL),
    ('Fight Club','David Fincher','director',NULL,NULL),
    ('Inception','Christopher Nolan','director',NULL,NULL),
    ('Star Wars: Episode V - The Empire Strikes Back','Irvin Kershner','director',NULL,NULL),
    ('The Matrix','Lana Wachowski','director',NULL,NULL),
    ('The Matrix','Lilly Wachowski','director',NULL,NULL),
    ('Goodfellas','Martin Scorsese','director',NULL,NULL),
    ('Interstellar','Christopher Nolan','director',NULL,NULL),
    ('One Flew Over the Cuckoo''s Nest','Miloš Forman','director',NULL,NULL),
    ('Se7en','David Fincher','director',NULL,NULL),
    ('The Shawshank Redemption','Tim Robbins','actor','Andy Dufresne',1),
    ('The Shawshank Redemption','Morgan Freeman','actor','Ellis "Red" Redding',2),
    ('The Shawshank Redemption','Bob Gunton','actor','Warden Norton',3),
    ('The Godfather','Marlon Brando','actor','Vito Corleone',1),
    ('The Godfather','Al Pacino','actor','Michael Corleone',2),
    ('The Godfather','James Caan','actor','Sonny Corleone',3),
    ('The Dark Knight','Christian Bale','actor','Bruce Wayne / Batman',1),
    ('The Dark Knight','Heath Ledger','actor','Joker',2),
    ('The Dark Knight','Aaron Eckhart','actor','Harvey Dent',3),
    ('The Godfather Part II','Al Pacino','actor','Michael Corleone',1),
    ('The Godfather Part II','Robert De Niro','actor','Vito Corleone',2),
    ('The Godfather Part II','Diane Keaton','actor','Kay Adams',3),
    ('12 Angry Men','Henry Fonda','actor','Juror 8',1),
    ('12 Angry Men','Lee J. Cobb','actor','Juror 3',2),
    ('12 Angry Men','Martin Balsam','actor','Juror 1',3),
    ('Schindler''s List','Liam Neeson','actor','Oskar Schindler',1),
    ('Schindler''s List','Ralph Fiennes','actor','Amon Göth',2),
    ('Schindler''s List','Ben Kingsley','actor','Itzhak Stern',3),
    ('The Lord of the Rings: The Return of the King','Elijah Wood','actor','Frodo Baggins',1),
    ('The Lord of the Rings: The Return of the King','Viggo Mortensen','actor','Aragorn',2),
    ('The Lord of the Rings: The Return of the King','Ian McKellen','actor','Gandalf',3),
    ('The Lord of the Rings: The Fellowship of the Ring','Elijah Wood','actor','Frodo Baggins',1),
    ('The Lord of the Rings: The Fellowship of the Ring','Ian McKellen','actor','Gandalf',2),
    ('The Lord of the Rings: The Fellowship of the Ring','Sean Astin','actor','Samwise Gamgee',3),
    ('Pulp Fiction','John Travolta','actor','Vincent Vega',1),
    ('Pulp Fiction','Samuel L. Jackson','actor','Jules Winnfield',2),
    ('Pulp Fiction','Uma Thurman','actor','Mia Wallace',3),
    ('The Good, the Bad and the Ugly','Clint Eastwood','actor','Blondie',1),
    ('The Good, the Bad and the Ugly','Eli Wallach','actor','Tuco',2),
    ('The Good, the Bad and the Ugly','Lee Van Cleef','actor','Angel Eyes',3),
    ('Forrest Gump','Tom Hanks','actor','Forrest Gump',1),
    ('Forrest Gump','Robin Wright','actor','Jenny Curran',2),
    ('Forrest Gump','Gary Sinise','actor','Lt. Dan Taylor',3),
    ('The Lord of the Rings: The Two Towers','Elijah Wood','actor','Frodo Baggins',1),
    ('The Lord of the Rings: The Two Towers','Viggo Mortensen','actor','Aragorn',2),
    ('The Lord of the Rings: The Two Towers','Ian McKellen','actor','Gandalf',3),
    ('Fight Club','Brad Pitt','actor','Tyler Durden',1),
    ('Fight Club','Edward Norton','actor','The Narrator',2),
    ('Fight Club','Helena Bonham Carter','actor','Marla Singer',3),
    ('Inception','Leonardo DiCaprio','actor','Dom Cobb',1),
    ('Inception','Joseph Gordon-Levitt','actor','Arthur',2),
    ('Inception','Elliot Page','actor','Ariadne',3),
    ('Star Wars: Episode V - The Empire Strikes Back','Mark Hamill','actor','Luke Skywalker',1),
    ('Star Wars: Episode V - The Empire Strikes Back','Harrison Ford','actor','Han Solo',2),
    ('Star Wars: Episode V - The Empire Strikes Back','Carrie Fisher','actor','Princess Leia',3),
    ('The Matrix','Keanu Reeves','actor','Neo',1),
    ('The Matrix','Laurence Fishburne','actor','Morpheus',2),
    ('The Matrix','Carrie-Anne Moss','actor','Trinity',3),
    ('Goodfellas','Ray Liotta','actor','Henry Hill',1),
    ('Goodfellas','Robert De Niro','actor','James Conway',2),
    ('Goodfellas','Joe Pesci','actor','Tommy DeVito',3),
    ('Interstellar','Matthew McConaughey','actor','Cooper',1),
    ('Interstellar','Anne Hathaway','actor','Brand',2),
    ('Interstellar','Jessica Chastain','actor','Murph',3),
    ('One Flew Over the Cuckoo''s Nest','Jack Nicholson','actor','Randle P. McMurphy',1),
    ('One Flew Over the Cuckoo''s Nest','Louise Fletcher','actor','Nurse Ratched',2),
    ('One Flew Over the Cuckoo''s Nest','Will Sampson','actor','Chief Bromden',3),
    ('Se7en','Brad Pitt','actor','David Mills',1),
    ('Se7en','Morgan Freeman','actor','William Somerset',2),
    ('Se7en','Kevin Spacey','actor','John Doe',3)
)
INSERT INTO movie_cast(movie_id, person_id, job, character_name, billing_order)
SELECT m.movie_id, p.person_id, v.job, v.character_name, v.billing_order
FROM v
JOIN movies m ON m.title = v.title
JOIN persons p ON p.name = v.person
;
